### ISSUE TITLE
Issues with API to MInio Integration

### ISSUE THREAD

**Issue by tokarthik** [reportportal/kubernetes#127] opened 2020-06-25 00:58 UTC
We are trying to deploy Reportportal V5. All the other services are coming up properly. However, API is not coming up when it reaches the stage of NIO file access for /plugins.

- Tested the Access KEYS/Passwd for MInio in command line - WORKING
- API can reach Minio IP - Working
- GUI Minio file/folder creation - WORKING
- API to MINIO step failing - FAILING

Could you please guide me about where is the issue?

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/info/InfoEndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.info.InfoEndpoint]: Factory method 'infoEndpoint' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'infoContributorComposite' defined in URL [jar:file:/service-api-5.2.2-exec.jar!/BOOT-INF/classes!/com/epam/ta/reportportal/info/InfoContributorComposite.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'extensionsInfoContributor': Unsatisfied dependency expressed through field 'pluginBox'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pf4jPluginBox' defined in class path resource [com/epam/ta/reportportal/core/configs/PluginConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.ta.reportportal.core.plugin.Pf4jPluginBox]: Factory method 'pf4jPluginBox' threw exception; nested exception is java.nio.file.AccessDeniedException: /plugins
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
        ... 61 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/info/InfoEndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.info.InfoEndpoint]: Factory method 'infoEndpoint' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'infoContributorComposite' defined in URL [jar:file:/service-api-5.2.2-exec.jar!/BOOT-INF/classes!/com/epam/ta/reportportal/info/InfoContributorComposite.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'extensionsInfoContributor': Unsatisfied dependency expressed through field 'pluginBox'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pf4jPluginBox' defined in class path resource [com/epam/ta/reportportal/core/configs/PluginConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.ta.reportportal.core.plugin.Pf4jPluginBox]: Factory method 'pf4jPluginBox' threw exception; nested exception is java.nio.file.AccessDeniedException: /plugins
```

**Comment by tokarthik** [comment] 2020-06-25 10:29
I am in the process of demo after poc done by local system is there information to help me regarding this issue.

**Comment by waynesun09** [comment] 2020-06-25 12:53
The permission issue could be resolved with update minio chart value `configPath` : 
https://github.com/waynesun09/reportportal-operator/issues/1#issuecomment-649520917

**Comment by naddison** [comment] 2020-07-28 20:14
I am getting this error as well when deploying to a on premise kubernetes, is this issue understood what the problem is? Is /plugin a folder trying to be read from minio?

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.ta.reportportal.core.plugin.Pf4jPluginBox]: Factory method 'pf4jPluginBox' threw exception; nested exception is java.nio.file.AccessDeniedException: /plugins
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 135 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /plugins
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at com.epam.ta.reportportal.plugin.Pf4jPluginManager.<init>(Pf4jPluginManager.java:97)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration.pf4jPluginBox(PluginConfiguration.java:70)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration$$EnhancerBySpringCGLIB$$575a8a95.CGLIB$pf4jPluginBox$1(<generated>)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration$$EnhancerBySpringCGLIB$$575a8a95$$FastClassBySpringCGLIB$$8c5ad73e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration$$EnhancerBySpringCGLIB$$575a8a95.pf4jPluginBox(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 136 common frames omitted
```

**Comment by Cyberglamdring** [comment] 2020-12-22 13:49
no response from requester

**Closed by Cyberglamdring** 2020-12-22 13:49 UTC
Labels: Check: DevOps, Waiting Info From Requestor
